/**
 * PagesConstants
 */
export class PagesConstants {
  static readonly SPLASH = "pages/Splash";
  static readonly SPLASH_FULL_SCREEN = "pages/SplashFullScreenAd";
  static readonly SPLASH_HALF_SCREEN = "pages/SplashHalfScreenAd";
  static readonly INDEX = "pages/Index";
  static readonly BANNER = "pages/Banner";
  static readonly NATIVE_AD = "pages/NativeAd";
  static readonly PLACEMENT_AD = "pages/PlacementAd";
}